name: Docker Build and Scan

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build-scan.yaml'
      - 'charts/**'

jobs:
  build-and-scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-app:test .

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb > trivy.deb
          sudo dpkg -i trivy.deb

      - name: Scan Docker image for vulnerabilities
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-app:test
