name: Helm Chart Package

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  package:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: helm package charts/my-app --destination packaged-charts
